package com.hblunch.order.auto.model;

import java.io.Serializable;

public class Test implements Serializable {
    /**
     * 
     * 表 : test
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : test
     * 对应字段 : name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @MBG Generated Thu Oct 12 15:48:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return test.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return test.name：
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     *
     * @param name  
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}