package com.hblunch.order.manual.dto;

import com.hblunch.base.BaseEntity;

import javax.persistence.Table;
import java.io.Serializable;
@Table(name="t_hb_login")
public class LoginDTO extends BaseEntity implements Serializable {
    /**
     * 
     * 表 : t_hb_login
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : t_hb_login
     * 对应字段 : login_name
     */
    private String loginName;

    /**
     * 
     * 表 : t_hb_login
     * 对应字段 : password
     */
    private String password;

    /**
     * 1 全局 2 部分地区
     * 表 : t_hb_login
     * 对应字段 : type
     */
    private String type;

    /**
     * 1 启用 2 作废
     * 表 : t_hb_login
     * 对应字段 : status
     */
    private String status;

    /**
     * 登录次数
     * 表 : t_hb_login
     * 对应字段 : login_count
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hb_login
     *
     * @MBG Generated Tue Oct 31 17:37:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_hb_login.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_login.login_name：
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * set method 
     *
     * @param loginName  
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_login.password：
     */
    public String getPassword() {
        return password;
    }

    /**
     * set method 
     *
     * @param password  
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_login.type：1 全局 2 部分地区
     */
    public String getType() {
        return type;
    }

    /**
     * set method 
     *
     * @param type  1 全局 2 部分地区
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_login.status：1 启用 2 作废
     */
    public String getStatus() {
        return status;
    }

    /**
     * set method 
     *
     * @param status  1 启用 2 作废
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_login.login_count：登录次数
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * set method 
     *
     * @param loginCount  登录次数
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", loginCount=").append(loginCount);
        sb.append("]");
        return sb.toString();
    }
}