package com.hblunch.order.manual.dto;

import com.hblunch.base.BaseEntity;

import javax.persistence.Table;
import java.io.Serializable;
@Table(name="t_hb_order_menu")
public class OrderMenuDTO extends BaseEntity implements Serializable {
    /**
     * 
     * 表 : t_hb_order_menu
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : t_hb_order_menu
     * 对应字段 : order_id
     */
    private String orderId;

    /**
     * 
     * 表 : t_hb_order_menu
     * 对应字段 : menu_id
     */
    private String menuId;

    /**
     * 
     * 表 : t_hb_order_menu
     * 对应字段 : menu_price
     */
    private String menuPrice;

    /**
     * 
     * 表 : t_hb_order_menu
     * 对应字段 : menu_name
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hb_order_menu
     *
     * @MBG Generated Thu Oct 26 17:29:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_hb_order_menu.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_order_menu.order_id：
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * set method 
     *
     * @param orderId  
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_order_menu.menu_id：
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * set method 
     *
     * @param menuId  
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_order_menu.menu_price：
     */
    public String getMenuPrice() {
        return menuPrice;
    }

    /**
     * set method 
     *
     * @param menuPrice  
     */
    public void setMenuPrice(String menuPrice) {
        this.menuPrice = menuPrice == null ? null : menuPrice.trim();
    }

    /**
     * get method 
     *
     * @return t_hb_order_menu.menu_name：
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * set method 
     *
     * @param menuName  
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", menuId=").append(menuId);
        sb.append(", menuPrice=").append(menuPrice);
        sb.append(", menuName=").append(menuName);
        sb.append("]");
        return sb.toString();
    }
}