package com.hblunch.order.manual.dto;

import com.hblunch.base.BaseEntity;

import javax.persistence.Table;
import java.io.Serializable;
@Table(name="t_hb_order")
public class OrderDTO extends BaseEntity implements Serializable {

    /**
     * 订单号
     * 表 : order
     * 对应字段 : orderid
     */
    private String orderid;

    /**
     * 下单时间
     * 表 : order
     * 对应字段 : orderdate
     */
    private String orderdate;

    /**
     * 类型
     * 表 : order
     * 对应字段 : type
     */
    private String type;

    /**
     * 店名
     * 表 : order
     * 对应字段 : storename
     */
    private String storename;

    /**
     * 点餐平台
     * 表 : order
     * 对应字段 : plation
     */
    private String plation;

    /**
     * 电话
     * 表 : order
     * 对应字段 : phone
     */
    private String phone;

    /**
     * 姓名
     * 表 : order
     * 对应字段 : name
     */
    private String name;

    /**
     * 送餐地址
     * 表 : order
     * 对应字段 : address
     */
    private String address;

    /**
     * 订单总额
     * 表 : order
     * 对应字段 : orderprice
     */
    private Long orderprice;

    /**
     * 订单详情 项目1:1,售价1:2,销售数1:3|项目2:1,售价2:2,销售数2:3
     * 表 : order
     * 对应字段 : items
     */
    private String items;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @MBG Generated Mon Oct 16 14:14:01 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return order.orderid：订单号
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * set method 
     *
     * @param orderid  订单号
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * get method 
     *
     * @return order.orderdate：下单时间
     */
    public String getOrderdate() {
        return orderdate;
    }

    /**
     * set method 
     *
     * @param orderdate  下单时间
     */
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate == null ? null : orderdate.trim();
    }

    /**
     * get method 
     *
     * @return order.type：类型
     */
    public String getType() {
        return type;
    }

    /**
     * set method 
     *
     * @param type  类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * get method 
     *
     * @return order.storename：店名
     */
    public String getStorename() {
        return storename;
    }

    /**
     * set method 
     *
     * @param storename  店名
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * get method 
     *
     * @return order.plation：点餐平台
     */
    public String getPlation() {
        return plation;
    }

    /**
     * set method 
     *
     * @param plation  点餐平台
     */
    public void setPlation(String plation) {
        this.plation = plation == null ? null : plation.trim();
    }

    /**
     * get method 
     *
     * @return order.phone：电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * set method 
     *
     * @param phone  电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * get method 
     *
     * @return order.name：姓名
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     *
     * @param name  姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get method 
     *
     * @return order.address：送餐地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * set method 
     *
     * @param address  送餐地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * get method 
     *
     * @return order.orderprice：订单总额
     */
    public Long getOrderprice() {
        return orderprice;
    }

    /**
     * set method 
     *
     * @param orderprice  订单总额
     */
    public void setOrderprice(Long orderprice) {
        this.orderprice = orderprice;
    }

    /**
     * get method 
     *
     * @return order.items：订单详情 项目1:1,售价1:2,销售数1:3|项目2:1,售价2:2,销售数2:3
     */
    public String getItems() {
        return items;
    }

    /**
     * set method 
     *
     * @param items  订单详情 项目1:1,售价1:2,销售数1:3|项目2:1,售价2:2,销售数2:3
     */
    public void setItems(String items) {
        this.items = items == null ? null : items.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", orderdate=").append(orderdate);
        sb.append(", type=").append(type);
        sb.append(", storename=").append(storename);
        sb.append(", plation=").append(plation);
        sb.append(", phone=").append(phone);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", orderprice=").append(orderprice);
        sb.append(", items=").append(items);
        sb.append("]");
        return sb.toString();
    }
}