package com.hblunch.order.manual.dto;

import com.hblunch.base.BaseEntity;

import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
@Table(name="t_hb_order")
public class OrderDTO extends BaseEntity implements Serializable{
    /**
     * 主键
     * 表 : t_hb_order
     * 对应字段 : id
     */
    private String id;

    /**
     * 订单号
     * 表 : t_hb_order
     * 对应字段 : order_id
     */
    private String orderId;

    /**
     * 下单时间
     * 表 : t_hb_order
     * 对应字段 : order_date
     */
    private String orderDate;

    /**
     * 类型
     * 表 : t_hb_order
     * 对应字段 : type
     */
    private String type;

    /**
     * 店名
     * 表 : t_hb_order
     * 对应字段 : store_name
     */
    private String storeName;

    /**
     * 点餐平台
     * 表 : t_hb_order
     * 对应字段 : plation
     */
    private String plation;

    /**
     * 电话
     * 表 : t_hb_order
     * 对应字段 : phone
     */
    private String phone;

    /**
     * 姓名
     * 表 : t_hb_order
     * 对应字段 : name
     */
    private String name;

    /**
     * 送餐地址
     * 表 : t_hb_order
     * 对应字段 : address
     */
    private String address;

    /**
     * 订单总额
     * 表 : t_hb_order
     * 对应字段 : order_price
     */
    private Long orderPrice;

    /**
     * 订单备注
     * 表 : t_hb_order
     * 对应字段 : items
     */
    private String items;
    @Transient
    private String menuName;
    @Transient
    private String menuCount;
    @Transient
    private String menuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hb_order
     *
     * @MBG Generated Fri Oct 27 09:54:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method
     *
     * @return t_hb_order.id：主键
     */
    public String getId() {
        return id;
    }

    /**
     * set method
     *
     * @param id  主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.order_id：订单号
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * set method
     *
     * @param orderId  订单号
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.order_date：下单时间
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * set method
     *
     * @param orderDate  下单时间
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate == null ? null : orderDate.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.type：类型
     */
    public String getType() {
        return type;
    }

    /**
     * set method
     *
     * @param type  类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.store_name：店名
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * set method
     *
     * @param storeName  店名
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.plation：点餐平台
     */
    public String getPlation() {
        return plation;
    }

    /**
     * set method
     *
     * @param plation  点餐平台
     */
    public void setPlation(String plation) {
        this.plation = plation == null ? null : plation.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.phone：电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * set method
     *
     * @param phone  电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.name：姓名
     */
    public String getName() {
        return name;
    }

    /**
     * set method
     *
     * @param name  姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.address：送餐地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * set method
     *
     * @param address  送餐地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * get method
     *
     * @return t_hb_order.order_price：订单总额
     */
    public Long getOrderPrice() {
        return orderPrice;
    }

    /**
     * set method
     *
     * @param orderPrice  订单总额
     */
    public void setOrderPrice(Long orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * get method
     *
     * @return t_hb_order.items：订单备注
     */
    public String getItems() {
        return items;
    }

    /**
     * set method
     *
     * @param items  订单备注
     */
    public void setItems(String items) {
        this.items = items == null ? null : items.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderDate=").append(orderDate);
        sb.append(", type=").append(type);
        sb.append(", storeName=").append(storeName);
        sb.append(", plation=").append(plation);
        sb.append(", phone=").append(phone);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", items=").append(items);
        sb.append("]");
        return sb.toString();
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuCount() {
        return menuCount;
    }

    public void setMenuCount(String menuCount) {
        this.menuCount = menuCount;
    }

    public String getMenuPrice() {
        return menuPrice;
    }

    public void setMenuPrice(String menuPrice) {
        this.menuPrice = menuPrice;
    }
}