package com.hblunch.order.manual.dto;


import com.hblunch.base.BaseEntity;

import javax.persistence.Table;
import java.io.Serializable;

@Table(name="test")
public class TestDTO  extends BaseEntity implements Serializable {
    /**
     * 
     * 表 : test
     * 对应字段 : name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @MBG Generated Thu Oct 12 15:48:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return test.name：
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     *
     * @param name  
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(super.getId());
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}